dev: &dev
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *dev
  database: cat_digital_db_dev

  
test:
  <<: *dev
  database: cat_digital_db_test


production:
  <<: *dev
  database: cat_digital_db_production
